!!com.example.app.properties.PropertiesData
appiumProperties:
 deviceName: device
 udid: Android
 app: C:\Users\ASUS\Downloads\alta-online-shop.apk
 automationName: UiAutomator2
 newCommandTimeout: 120
 autoGrantPermissions: true
 appiumUrl: http://localhost:4723/wd/hub/
